name = "AIThreatIntelSystem"
version = "0.1.0"
authors = ["AI Agent <ai.agent@example.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d09b"
Clustering = "aaaa0939-5af0-5ca9-8880-0cee703560cf" # Added
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLJ = "add582a8-1359-11e9-1e9a-2106979357bb" # Added
StatsBase = "2913bbd2-ae8a-5f71-8c99-42f6c13210ba" # Added

[compat]
julia = "1.6"
CSV = "0.10"
Clustering = "0.15" # Added - Check for latest compatible version with Julia 1.6 / MLJ
DataFrames = "1.5"
JSON = "0.21"
Dates = "1"
Logging = "1.2"
MLJ = "0.18" # Added - Check for latest compatible version with Julia 1.6
StatsBase = "0.33" # Added - Check for latest compatible version
